### ISSUE TITLE
Failed assertion in HelloWorld

### ISSUE THREAD

**Issue by Ahdhn** [pradeep-pyro/RCube#11]
This happens when I try to expand the `objects` menu on Debug mode 

![Untitled](https://user-images.githubusercontent.com/3890167/71936470-591d4a00-315e-11ea-803e-2ad421abd2c5.png)

The failed assertion is [here](https://github.com/pradeep-pyro/RCube/blob/master/include/RCube/Core/Arch/World.h#L172)

**Comment by pradeep-pyro** [comment]
The problem was that we have a "(None)" item in the dropdown box which actually does not correspond to an entity, and I was trying to access its components.
