### ISSUE TITLE
Fix assumption in `MeshData::valid()` 

### ISSUE THREAD

**Issue by Ahdhn** [pradeep-pyro/RCube#14]
The assumption that the mesh will have vertex normal, texture, and color does not always hold especially if the mesh is loaded from OBJ file
https://github.com/pradeep-pyro/RCube/blob/master/src/RCube/Core/Graphics/OpenGL/Mesh.cpp#L44
The mesh may not have texture but still be valid to work with.

**Comment by Ahdhn** [comment]
What was the conclusion here? @pradeep-pyro

**Comment by pradeep-pyro** [comment]
It is a wrong assumption in general even if we don't have OBJ files. We should ideally check for #vertices != 0, and whether other attributes are either empty or match with #vertices. I will fix it soon 👍
